#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 FoBE Studio
# SPDX-License-Identifier: Apache-2.0
"""Import the pinned upstream font arrays, excluding WenQuanYi and Unifont.

The input must be the exact upstream file recorded in fonts/sources.json.
This does not download sources or rebuild glyphs. It adds local Kconfig guards
and generates Kconfig.fonts while preserving every retained array byte and its
upstream attribution. It also removes excluded declarations from the otherwise
independently maintained public U8G2 header.
"""

import argparse
from pathlib import Path
import re

from font_inventory import ARRAY, SOURCE, ROOT, excluded, load_records, parse_fonts, reference_fonts


def render_fonts(text, wrap_before_symbol):
    output = [
        "/*\n  u8g2_fonts.c\n",
        "  Generated by import_fonts.py from the pinned upstream source.\n",
        "  WenQuanYi and Unifont are excluded; see fonts/README.md.\n*/\n",
        "#include <display/u8g2.h>\n\n",
    ]
    for match in ARRAY.finditer(text):
        symbol = match.group(1)
        if excluded(symbol):
            continue
        start = text.rfind("/*", 0, match.start())
        end = text.find("*/", start) + 2
        output.append(text[start:end] + "\n")
        upstream_guard = text[end:match.start()].strip()
        if upstream_guard not in ("", "#ifdef U8G2_USE_LARGE_FONTS"):
            raise ValueError(f"Unexpected upstream font guard: {symbol}")
        if upstream_guard:
            output.append(upstream_guard + "\n")
        option = "CONFIG_U8G2_FONT_" + symbol.upper()
        output.append(f"#if defined(CONFIG_U8G2_FONT_ALL) || defined({option})\n")
        lines = match.group(0).splitlines()
        declaration = lines[0].rstrip()
        indentation = "    "
        # Preserve the existing pinned import's two long-declaration layouts.
        # The small exceptional list is recorded with the import selection.
        if symbol in wrap_before_symbol:
            declaration = declaration.replace("const uint8_t ", "const uint8_t\n    ", 1)
            indentation = "        "
        elif len(declaration) > 100:
            declaration = declaration.replace('(\"', '(\n    \"', 1)
        output.append(declaration + "\n")
        output.extend(indentation + line.strip() + "\n" for line in lines[1:])
        output.append(f"#endif /* {option} ({symbol}) */\n")
        if upstream_guard:
            output.append("#endif /* U8G2_USE_LARGE_FONTS */\n")
    return "".join(output)


def render_kconfig(fonts):
    output = [
        "# SPDX-FileCopyrightText: FoBE Studio\n",
        "# SPDX-License-Identifier: Apache-2.0\n",
        "# Auto-generated by scripts/import_fonts.py.\n",
        "# Keep sorted for stable diffs.\n\n",
    ]
    for symbol in sorted(fonts):
        output.append(f"config U8G2_FONT_{symbol.upper()}\n")
        output.append(f'\tbool "{symbol}" if !U8G2_FONT_ALL\n\n')
    return "".join(output).rstrip() + "\n"


def filter_header(text):
    text = re.sub(
        r'^extern\s+const\s+uint8_t\s+u8g2_font_(?:wqy|unifont)\w*'
        r'\s*\[\][^;]*;\n', "", text, flags=re.MULTILINE,
    )
    return re.sub(r'^#define u8g_font_unifont\w*[^\n]*\n', "", text, flags=re.MULTILINE)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-fonts", type=Path, required=True)
    parser.add_argument("--check", action="store_true", help="compare without writing files")
    args = parser.parse_args()
    _, manifest = load_records()
    fonts = reference_fonts(args.reference_fonts, manifest)
    wrap_before_symbol = set(manifest["font_selection"]["declaration_wrap_before_symbol"])
    if not wrap_before_symbol <= fonts.keys():
        raise ValueError("Font declaration layout refers to absent symbols")
    rendered = render_fonts(args.reference_fonts.read_text(errors="replace"), wrap_before_symbol)
    if parse_fonts(rendered) != fonts:
        raise ValueError("Generated font bytes or attribution differ from the upstream selection")
    header = ROOT / "include/display/u8g2.h"
    outputs = {
        SOURCE / "u8g2_fonts.c": rendered,
        ROOT / "Kconfig.fonts": render_kconfig(fonts),
        header: filter_header(header.read_text()),
    }
    for path, content in outputs.items():
        if args.check:
            if path.read_text() != content:
                raise ValueError(f"Generated file is stale: {path.relative_to(ROOT)}")
        else:
            path.write_text(content)
    print(f"{'Checked' if args.check else 'Imported'} {len(fonts)} fonts; "
          "WenQuanYi and Unifont excluded")


if __name__ == "__main__":
    main()
